/* Generated by scripts/dither.mjs from images.manifest.json — do not edit. */
export const imagesHash = '60df608c';

export type Tone = "paper" | "navy" | "frost" | "azure" | "ink";
export type ImageVariant = Tone;
export interface ImageCredit {
  title: string;
  author: string;
  year: number | null;
  licence: string;
  licence_url: string;
  page_url: string;
  source: string;
}
export interface GeneratedImage {
  alt: string;
  aspect: number;
  variants: Partial<Record<ImageVariant, Record<number, string>>>;
  credit: ImageCredit;
}

export const images = {
  "suspended": {
    "alt": "A garden spider letting itself down from a leafy twig on a single thread. Wood engraving.",
    "aspect": 0.7960199004975125,
    "variants": {
      "paper": {
        "720": "images/suspended-720-paper.png",
        "1440": "images/suspended-1440-paper.png"
      },
      "azure": {
        "720": "images/suspended-720-azure.png",
        "1440": "images/suspended-1440-azure.png"
      }
    },
    "credit": {
      "title": "Epeira diadema suspended by its thread (Popular Science Monthly, vol. 50)",
      "author": "Unknown engraver",
      "year": 1896,
      "licence": "Public domain",
      "licence_url": "https://commons.wikimedia.org/wiki/Template:PD-old",
      "page_url": "https://commons.wikimedia.org/wiki/File:PSM_V50_D391_Epeira_diadema_suspended_by_its_thread.jpg",
      "source": "Wikimedia Commons"
    }
  },
  "dew": {
    "alt": "A sector of an orb web strung with dew, every thread a line of bright beads against black. Engraving.",
    "aspect": 0.712166172106825,
    "variants": {
      "navy": {
        "720": "images/dew-720-navy.png",
        "1440": "images/dew-1440-navy.png"
      }
    },
    "credit": {
      "title": "Sector of a dew-laden orb web (Popular Science Monthly, vol. 37)",
      "author": "Unknown engraver",
      "year": 1890,
      "licence": "Public domain",
      "licence_url": "https://commons.wikimedia.org/wiki/Template:PD-old",
      "page_url": "https://commons.wikimedia.org/wiki/File:PSM_V37_D052_Sector_of_a_dew_laden_orb_web.jpg",
      "source": "Wikimedia Commons"
    }
  },
  "argiope": {
    "alt": "A banded garden spider resting head-down at the centre of its web, legs paired along the zigzag silk. Line engraving.",
    "aspect": 0.7960199004975125,
    "variants": {
      "paper": {
        "720": "images/argiope-720-paper.png",
        "1440": "images/argiope-1440-paper.png"
      }
    },
    "credit": {
      "title": "Argiope at the hub of its web (American Spiders and Their Spinningwork)",
      "author": "Henry C. McCook",
      "year": 1890,
      "licence": "Public domain",
      "licence_url": "https://commons.wikimedia.org/wiki/Template:PD-old",
      "page_url": "https://commons.wikimedia.org/wiki/File:American_spiders_and_their_spinningwork._A_natural_history_of_the_orbweaving_spiders_of_the_United_States,_with_special_regard_to_their_industry_and_habits_(1890)_(14591579638).jpg",
      "source": "Internet Archive Book Images"
    }
  },
  "hokusai": {
    "alt": "Mount Fuji seen through a spider web strung across the foreground, a spider waiting below. Woodblock print.",
    "aspect": 0.6707033069399162,
    "variants": {
      "paper": {
        "720": "images/hokusai-720-paper.png",
        "1440": "images/hokusai-1440-paper.png"
      },
      "azure": {
        "720": "images/hokusai-720-azure.png",
        "1440": "images/hokusai-1440-azure.png"
      }
    },
    "credit": {
      "title": "Fuji behind a spider web (One Hundred Views of Mount Fuji)",
      "author": "Katsushika Hokusai",
      "year": 1835,
      "licence": "Public domain",
      "licence_url": "https://commons.wikimedia.org/wiki/Template:PD-old",
      "page_url": "https://commons.wikimedia.org/wiki/File:Hokusai_Mt_Fuji_Behind_a_Spider_Net.jpg",
      "source": "Wikimedia Commons"
    }
  },
  "geometric": {
    "alt": "A perfect orb web drawn as geometry, its spider waiting at the edge. Wood engraving.",
    "aspect": 1.0285714285714285,
    "variants": {
      "paper": {
        "720": "images/geometric-720-paper.png",
        "1440": "images/geometric-1440-paper.png"
      },
      "azure": {
        "720": "images/geometric-720-azure.png",
        "1440": "images/geometric-1440-azure.png"
      }
    },
    "credit": {
      "title": "The geometric net of Epeira diadema (The Penny Magazine)",
      "author": "Unknown engraver",
      "year": 1834,
      "licence": "Public domain",
      "licence_url": "https://commons.wikimedia.org/wiki/Template:PD-old",
      "page_url": "https://commons.wikimedia.org/wiki/File:Penny_Magazine_1834_131_Geometric_Net_of_Epeira_diadema.jpg",
      "source": "Wikimedia Commons"
    }
  },
  "garden-web": {
    "alt": "An orb web framed by twigs and leaves, the spiral fine as hair. Wood engraving.",
    "aspect": 1.3162705667276051,
    "variants": {
      "paper": {
        "720": "images/garden-web-720-paper.png",
        "1440": "images/garden-web-1440-paper.png"
      }
    },
    "credit": {
      "title": "Web of the garden spider (Popular Science Monthly, vol. 33)",
      "author": "Unknown engraver",
      "year": 1888,
      "licence": "Public domain",
      "licence_url": "https://commons.wikimedia.org/wiki/Template:PD-old",
      "page_url": "https://commons.wikimedia.org/wiki/File:PSM_V33_D817_Web_of_the_garden_spider.jpg",
      "source": "Wikimedia Commons"
    }
  },
  "snare": {
    "alt": "A round web with its spider at the hub and a fly caught near the rim. Wood engraving.",
    "aspect": 0.9448818897637795,
    "variants": {
      "paper": {
        "720": "images/snare-720-paper.png",
        "1440": "images/snare-1440-paper.png"
      }
    },
    "credit": {
      "title": "Snare of the long-bodied garden spider (Popular Science Monthly, vol. 50)",
      "author": "Unknown engraver",
      "year": 1896,
      "licence": "Public domain",
      "licence_url": "https://commons.wikimedia.org/wiki/Template:PD-old",
      "page_url": "https://commons.wikimedia.org/wiki/File:PSM_V50_D392_Snare_of_long_bodied_garden_spider_tretnagnatha_extensa.jpg",
      "source": "Wikimedia Commons"
    }
  },
  "foxglove": {
    "alt": "A spider web stretched between a pine bough and a foxglove, bending in the wind. Wood engraving.",
    "aspect": 0.7969009407858328,
    "variants": {
      "paper": {
        "720": "images/foxglove-720-paper.png",
        "1440": "images/foxglove-1440-paper.png"
      },
      "azure": {
        "720": "images/foxglove-720-azure.png",
        "1440": "images/foxglove-1440-azure.png"
      }
    },
    "credit": {
      "title": "Pine, foxglove, spiderweb, wind",
      "author": "Unknown engraver",
      "year": 1873,
      "licence": "Public domain",
      "licence_url": "https://commons.wikimedia.org/wiki/Template:PD-old",
      "page_url": "https://commons.wikimedia.org/wiki/File:Pine,_Foxglove,_Spiderweb,_Wind.jpg",
      "source": "Wikimedia Commons"
    }
  },
  "mankes": {
    "alt": "A garden spider at the centre of its orb web, every radial thread and spiral lit white against black. Wood engraving.",
    "aspect": 0.8977556109725686,
    "variants": {
      "navy": {
        "720": "images/mankes-720-navy.png",
        "1440": "images/mankes-1440-navy.png"
      }
    },
    "credit": {
      "title": "Kruisspin in zijn web (Garden spider in its web)",
      "author": "Jan Mankes",
      "year": 1916,
      "licence": "CC0 1.0",
      "licence_url": "https://creativecommons.org/publicdomain/zero/1.0/",
      "page_url": "https://commons.wikimedia.org/wiki/File:Kruisspin_in_zijn_web,_RP-P-1921-1932.jpg",
      "source": "Rijksmuseum, Amsterdam"
    }
  },
  "graag": {
    "alt": "A cross spider seen from above, sitting in the middle of its web; the threads cut white out of black. Woodcut.",
    "aspect": 0.7821835958718087,
    "variants": {
      "paper": {
        "720": "images/graag-720-paper.png",
        "1440": "images/graag-1440-paper.png"
      },
      "azure": {
        "720": "images/graag-720-azure.png",
        "1440": "images/graag-1440-azure.png"
      }
    },
    "credit": {
      "title": "Spin in een web (Spider in a web)",
      "author": "Julie de Graag",
      "year": 1918,
      "licence": "CC0 1.0",
      "licence_url": "https://creativecommons.org/publicdomain/zero/1.0/",
      "page_url": "https://commons.wikimedia.org/wiki/File:Spin_in_een_web,_RP-P-1935-907.jpg",
      "source": "Rijksmuseum, Amsterdam"
    }
  },
  "tempesta": {
    "alt": "Minerva, helmeted, points at Arachne beside her loom as the weaver is turned into a spider. Etching.",
    "aspect": 1.2754650132860939,
    "variants": {
      "paper": {
        "720": "images/tempesta-720-paper.png",
        "1440": "images/tempesta-1440-paper.png"
      },
      "azure": {
        "720": "images/tempesta-720-azure.png",
        "1440": "images/tempesta-1440-azure.png"
      }
    },
    "credit": {
      "title": "Minerva verandert Arachne in een spin (Minerva turns Arachne into a spider)",
      "author": "Antonio Tempesta",
      "year": 1606,
      "licence": "CC0 1.0",
      "licence_url": "https://creativecommons.org/publicdomain/zero/1.0/",
      "page_url": "https://commons.wikimedia.org/wiki/File:Minerva_verandert_Arachne_in_een_spin,_RP-P-OB-37.828.jpg",
      "source": "Rijksmuseum, Amsterdam"
    }
  },
  "luyken": {
    "alt": "Two men in a landscape stop to study a spider web strung between the branches of a tree. Etching.",
    "aspect": 1.1612903225806452,
    "variants": {
      "paper": {
        "720": "images/luyken-720-paper.png",
        "1440": "images/luyken-1440-paper.png"
      },
      "azure": {
        "720": "images/luyken-720-azure.png",
        "1440": "images/luyken-1440-azure.png"
      }
    },
    "credit": {
      "title": "Embleem spin: twee mannen bekijken een spinnenweb (Two men study a spider web)",
      "author": "Jan Luyken",
      "year": 1700,
      "licence": "CC0 1.0",
      "licence_url": "https://creativecommons.org/publicdomain/zero/1.0/",
      "page_url": "https://commons.wikimedia.org/wiki/File:Embleem_spin_Twee_mannen_bekijken_een_spinnenweb,_RP-P-OB-44.857.jpg",
      "source": "Rijksmuseum, Amsterdam"
    }
  },
  "weiditz": {
    "alt": "An armoured Minerva beside a huge spider web hung between trees, its spider at the centre. Woodcut.",
    "aspect": 1.4342629482071714,
    "variants": {
      "paper": {
        "720": "images/weiditz-720-paper.png",
        "1440": "images/weiditz-1440-paper.png"
      },
      "azure": {
        "720": "images/weiditz-720-azure.png",
        "1440": "images/weiditz-1440-azure.png"
      }
    },
    "credit": {
      "title": "Minerva als strijder bij een spinnenweb met spin (Minerva beside a spider web)",
      "author": "Hans Weiditz (II)",
      "year": 1532,
      "licence": "CC0 1.0",
      "licence_url": "https://creativecommons.org/publicdomain/zero/1.0/",
      "page_url": "https://commons.wikimedia.org/wiki/File:Minerva_als_strijder_bij_een_spinnenweb_met_spin,_RP-P-1874-11-6-1.jpg",
      "source": "Rijksmuseum, Amsterdam"
    }
  },
  "vault": {
    "alt": "A vaulted ceiling seen from below, a vast spider web spanning it from rib to rib. Woodcut.",
    "aspect": 0.6795658329400661,
    "variants": {
      "paper": {
        "720": "images/vault-720-paper.png",
        "1440": "images/vault-1440-paper.png"
      },
      "azure": {
        "720": "images/vault-720-azure.png",
        "1440": "images/vault-1440-azure.png"
      }
    },
    "credit": {
      "title": "Gewelf met spinnenweb (Vault with a spider web)",
      "author": "Hans Weiditz (II)",
      "year": 1532,
      "licence": "CC0 1.0",
      "licence_url": "https://creativecommons.org/publicdomain/zero/1.0/",
      "page_url": "https://commons.wikimedia.org/wiki/File:Gewelf_met_spinnenweb,_RP-P-1874-11-72-1.jpg",
      "source": "Rijksmuseum, Amsterdam"
    }
  },
  "dijsselhof": {
    "alt": "A decorative title band: a cross spider at the hub of a half-wheel web, threads radiating across a dark field. Woodcut.",
    "aspect": 1.9753086419753085,
    "variants": {
      "paper": {
        "720": "images/dijsselhof-720-paper.png",
        "1440": "images/dijsselhof-1440-paper.png"
      },
      "navy": {
        "720": "images/dijsselhof-720-navy.png",
        "1440": "images/dijsselhof-1440-navy.png"
      }
    },
    "credit": {
      "title": "Titelhoofd met kruisspin en spinnenweb (Title head with a cross spider and web)",
      "author": "Gerrit Willem Dijsselhof",
      "year": 1893,
      "licence": "CC0 1.0",
      "licence_url": "https://creativecommons.org/publicdomain/zero/1.0/",
      "page_url": "https://commons.wikimedia.org/wiki/File:Titelhoofd_met_kruisspin_en_spinnenweb,_RP-P-1944-2688.jpg",
      "source": "Rijksmuseum, Amsterdam"
    }
  }
} as const satisfies Record<string, GeneratedImage>;

export type ImageId = keyof typeof images;
