"""Spiyweb - graph-based retrieval driven by spreading activation."""

from spiyweb.config import (
    ColoredRetrievalConfig,
    ConflictConfig,
    ConsolidationConfig,
    CorpusLintConfig,
    DedupConfig,
    EdgeLayer,
    EmbeddingConfig,
    EntityEdgeConfig,
    EntityExtractionConfig,
    LayerWeights,
    LearnedLayerConfig,
    LLMConfig,
    MassConfig,
    NegativeSeedConfig,
    NLICandidateConfig,
    NLIEdgeConfig,
    NLIModelConfig,
    OutputConfig,
    PolarityConfig,
    PropagationConfig,
    PropositionConfig,
    RetrievalConfig,
    SemanticEdgeConfig,
    StructuralEdgeConfig,
    ThermalConfig,
    TraceConfig,
)
from spiyweb.core.colors import ColoredResult, propagate_colored
from spiyweb.core.conflict import (
    ConflictRecord,
    NegativeEdge,
    conflict_adjacency,
    neutralize,
)
from spiyweb.core.dedup import SimilarityFn, adaptive_threshold, find_survivor
from spiyweb.core.graph import Graph, Node, NodeLayer, Polarity
from spiyweb.core.mass import node_masses
from spiyweb.core.negative import AbsorptionRecord, negative_field
from spiyweb.core.polarity import DisputeRecord
from spiyweb.core.propagate import Activation, PropagationResult, propagate
from spiyweb.edges.consolidate import ConsolidationReport, EdgeUsage, prune_layers
from spiyweb.edges.derivation import build_derivation_edges
from spiyweb.edges.learned import LearnedLayer
from spiyweb.edges.nli import NLIModel, build_nli_edges
from spiyweb.ledger import Destroyed, Ledger, build_ledger, destroyed_per_node
from spiyweb.lint import Finding, LintReport, lint_corpus, source_summary
from spiyweb.nli import TransformersNLIModel, contradiction_label_index
from spiyweb.nodes.propositions import Proposition, extract_propositions
from spiyweb.output import (
    ActivationPath,
    DisputeWarning,
    GapWarning,
    RefusalReport,
    ThemeCluster,
    activation_paths,
    build_refusal_report,
    color_composition,
    dispute_warnings,
    entity_edge_labels,
    gap_warnings,
    theme_clusters,
)
from spiyweb.profiles import (
    COMPARE,
    DEFAULT_PROFILE,
    EXPLORE,
    PRECISE,
    PROFILES,
    Profile,
)
from spiyweb.questions import ConflictQuestion, build_conflict_question
from spiyweb.retrieve import (
    ColoredRetrievalResult,
    Confidence,
    RetrievalResult,
    SeedSource,
    retrieve,
    retrieve_colored,
)
from spiyweb.session import (
    Answer,
    ColoredAnswer,
    Passage,
    SpiywebIndex,
    open_index,
)
from spiyweb.thermal import ThermalSession
from spiyweb.trace import TraceLedger, TraceRecord, TraceStore, load_traces

__version__ = "0.1.2"

__all__ = [
    "COMPARE",
    "DEFAULT_PROFILE",
    "EXPLORE",
    "PRECISE",
    "PROFILES",
    "AbsorptionRecord",
    "Activation",
    "ActivationPath",
    "Answer",
    "ColoredAnswer",
    "ColoredResult",
    "ColoredRetrievalConfig",
    "ColoredRetrievalResult",
    "Confidence",
    "ConflictConfig",
    "ConflictQuestion",
    "ConflictRecord",
    "ConsolidationConfig",
    "ConsolidationReport",
    "CorpusLintConfig",
    "DedupConfig",
    "Destroyed",
    "DisputeRecord",
    "DisputeWarning",
    "EdgeLayer",
    "EdgeUsage",
    "EmbeddingConfig",
    "EntityEdgeConfig",
    "EntityExtractionConfig",
    "Finding",
    "GapWarning",
    "Graph",
    "LLMConfig",
    "LayerWeights",
    "LearnedLayer",
    "LearnedLayerConfig",
    "Ledger",
    "LintReport",
    "MassConfig",
    "NLICandidateConfig",
    "NLIEdgeConfig",
    "NLIModel",
    "NLIModelConfig",
    "NegativeEdge",
    "NegativeSeedConfig",
    "Node",
    "NodeLayer",
    "OutputConfig",
    "Passage",
    "Polarity",
    "PolarityConfig",
    "Profile",
    "PropagationConfig",
    "PropagationResult",
    "Proposition",
    "PropositionConfig",
    "RefusalReport",
    "RetrievalConfig",
    "RetrievalResult",
    "SeedSource",
    "SemanticEdgeConfig",
    "SimilarityFn",
    "SpiywebIndex",
    "StructuralEdgeConfig",
    "ThemeCluster",
    "ThermalConfig",
    "ThermalSession",
    "TraceConfig",
    "TraceLedger",
    "TraceRecord",
    "TraceStore",
    "TransformersNLIModel",
    "__version__",
    "activation_paths",
    "adaptive_threshold",
    "build_conflict_question",
    "build_derivation_edges",
    "build_ledger",
    "build_nli_edges",
    "build_refusal_report",
    "color_composition",
    "conflict_adjacency",
    "contradiction_label_index",
    "destroyed_per_node",
    "dispute_warnings",
    "entity_edge_labels",
    "extract_propositions",
    "find_survivor",
    "gap_warnings",
    "lint_corpus",
    "load_traces",
    "negative_field",
    "neutralize",
    "node_masses",
    "open_index",
    "propagate",
    "propagate_colored",
    "prune_layers",
    "retrieve",
    "retrieve_colored",
    "source_summary",
    "theme_clusters",
]
